# Generated by Django 5.2.7 on 2026-01-07 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, upload_to='cat_images/'),
        ),
        migrations.AddField(
            model_name='cat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
