# Generated by Django 5.2.7 on 2026-01-17 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cat_image_alter_cat_price_alter_cat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveSmallIntegerField(max_length=2, verbose_name='age (in years)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
